spring:
  rabbitmq:
    host: jaragua.lmq.cloudamqp.com
    port: 5671
    username: wfiygbgc
    password: EFTpuSfIZrWOqZOJoVBUNgNGgtLoBRxB
    virtual-host: wfiygbgc
    acknowledge-mode: auto
    ssl:
      enabled: true
      

  application:
    name: pagtos-api

server:
  port: 9093

logging:
  level:
    root: INFO
    org.springframework.amqp: DEBUG
    br.edu.utfpr.msg.pagamentos: DEBUG

custom:
  config:
    max-retries: 5
    retry-interval: 1000